[build]
builder = "dockerfile"

[deploy]
startCommand = "poetry run python start.py"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
FLASK_APP = "line_qa_system.app"
FLASK_ENV = "production"
PORT = "8000"
DEBUG = "false"
