[build]
builder = "dockerfile"

[deploy]
startCommand = "poetry run python -m flask run --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
FLASK_ENV = "production"
DEBUG = "false"
